title: Think
description: AI Automation & Data Skills
theme: jekyll-theme-minimal   # any GitHub-supported theme works
show_downloads: false
favicon: /favicon.ico         # optional – add later if desired
